---
name: RaspberryMatic CCU (Proxy)
version: 0.2.6
stage: experimental
slug: raspberrymatic_proxy
image: ghcr.io/jens-maus/raspberrymatic-proxy
arch:
  - armv7
  - aarch64
  - amd64
  - armhf
  - i386
description: Proxy to externally running RaspberryMatic CCU
url: https://github.com/jens-maus/RaspberryMatic
ingress: true
ingress_stream: true
panel_title: RaspberryMatic WebUI
panel_icon: mdi:router-wireless
boot: auto
init: true
timeout: 30
options:
  server: "http://homematic-raspi:80"
schema:
  server: url?
map:
  - config:ro
environment:
  HM_HAPROXY_SRC: 172.30.32.2/32
