---
name: Release Build (HA Proxy-Addon)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build HA Proxy-Addon
    # strategy:
    #  matrix:
    #    arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./home-assistant-addon-proxy"

      - name: Set Environment
        run: |
          echo "IMAGE=$(echo ${{ steps.info.outputs.image }} | cut -d'/' -f3)" >> $GITHUB_ENV;
          if [[ -z "${{ github.head_ref }}" ]] && [[ "${{ github.event_name }}" == "push" ]]; then
            echo "BUILD_ARGS=" >> $GITHUB_ENV;
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.7.1
        with:
          install: true

      - name: Login to GitHub Container Registry
        if: env.BUILD_ARGS != '--test'
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.description=Alternative OS for your homematicIP CCU
            org.opencontainers.image.vendor=RasperryMatic OpenSource Project
            org.opencontainers.image.authors=RaspberryMatic OpenSource Team
            org.opencontainers.image.url=https://raspberrymatic.de
          annotations: |
            org.opencontainers.image.description=Alternative OS for your homematicIP CCU
            org.opencontainers.image.vendor=RasperryMatic OpenSource Project
            org.opencontainers.image.authors=RaspberryMatic OpenSource Team
            org.opencontainers.image.url=https://raspberrymatic.de
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Build and push container image
        uses: docker/build-push-action@v6.9.0
        id: docker_build
        with:
          context: home-assistant-addon-proxy
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: false

      # - name: Build+Push add-on
      #  uses: home-assistant/builder@2024.08.2
      #  with:
      #    args: |
      #      ${{ env.BUILD_ARGS }} \
      #      --all
      #      --target /data/home-assistant-addon-proxy \
      #      --image "${{ env.IMAGE }}" \
      #      --docker-hub "ghcr.io/${{ github.repository_owner }}" \
      #      --addon
